# QUESTION 1

In [1]:
import numpy as np

np.random.rand(3,3,3)

array([[[0.79122017, 0.40186074, 0.70801991],
        [0.53356392, 0.52786627, 0.27417493],
        [0.36703368, 0.87578386, 0.58446291]],

       [[0.61703027, 0.15202521, 0.49776715],
        [0.11081315, 0.1385543 , 0.46540857],
        [0.11013453, 0.32915272, 0.67277767]],

       [[0.09312904, 0.78103398, 0.26548237],
        [0.43091386, 0.82649807, 0.39164058],
        [0.93610728, 0.19634105, 0.7782679 ]]])

# QUESTION 2

In [2]:
np.diag(np.arange(1,5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# QUESTION 3

In [3]:
a = np.ones((8,8))
a[1::2,::2] = 0
a[::2,1::2] = 0
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

# QUESTION 4

In [7]:
a = np.random.randint(10,50,size=(5,5))
print("Original Array:")
print(a)
amax, amin = a.max(), a.min()
a = (a - amin)/(amax - amin)
print("After normalization:")
print(a)

Original Array:
[[31 23 25 46 33]
 [39 13 44 42 20]
 [31 40 43 46 49]
 [46 15 24 34 45]
 [39 40 39 27 16]]
After normalization:
[[0.5        0.27777778 0.33333333 0.91666667 0.55555556]
 [0.72222222 0.         0.86111111 0.80555556 0.19444444]
 [0.5        0.75       0.83333333 0.91666667 1.        ]
 [0.91666667 0.05555556 0.30555556 0.58333333 0.88888889]
 [0.72222222 0.75       0.72222222 0.38888889 0.08333333]]


# QUESTION 5

In [10]:
f=np.array([1,2,3,4,5])
print("1st array :-")
print(f)
g=np.array([2,4,6,8,10])
print("2nd array :-")
print(g)
com_values=np.intersect1d(f,g)
print("Common values between two arrays :-")
print(com_values)

1st array :-
[1 2 3 4 5]
2nd array :-
[ 2  4  6  8 10]
Common values between two arrays :-
[2 4]


# QUESTION 6

In [9]:
print("Date yesterday:", np.datetime64('today') - np.timedelta64(1, 'D'))
print("Date today    :", np.datetime64('today'))
print("Date tomorrow :", np.datetime64('today') + np.timedelta64(1, 'D'))

Date yesterday: 2020-07-25
Date today    : 2020-07-26
Date tomorrow : 2020-07-27


# QUESTION 7

In [12]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print('Are the two arrays equal :- ',np.array_equal(x,y))

Are the two arrays equal :-  False


In [13]:
m = np.array([1,2,3])
n = np.array([1,2,3])
print('Are the two arrays equal :- ',np.array_equal(m,n))

Are the two arrays equal :-  True


# QUESTION 8

In [22]:
a = np.random.randn(10,1)
print('Original Array :- ')
print(a)
a[a == a.max()] = 0
print('After replacing maximum value by 0 :-')
print(a)

Original Array :- 
[[-0.32596162]
 [ 1.06391942]
 [ 0.33173778]
 [ 0.23984388]
 [-0.41196146]
 [ 2.16418272]
 [ 1.72132171]
 [-0.86041861]
 [-0.05304817]
 [ 0.56699106]]
After replacing maximum value by 0 :-
[[-0.32596162]
 [ 1.06391942]
 [ 0.33173778]
 [ 0.23984388]
 [-0.41196146]
 [ 0.        ]
 [ 1.72132171]
 [-0.86041861]
 [-0.05304817]
 [ 0.56699106]]


# QUESTION 9

In [26]:
l=np.random.randn(3,5)
print(l)
for i in range(len(l)):
    print(l[i])

[[ 1.49973622  0.66821674  1.18433716  0.21467392 -1.6069926 ]
 [ 0.47323223  0.21508137 -0.6363411  -1.61474173  2.34223874]
 [-0.56409102 -0.88934947  0.18253626  1.53009048  0.96155976]]
[ 1.49973622  0.66821674  1.18433716  0.21467392 -1.6069926 ]
[ 0.47323223  0.21508137 -0.6363411  -1.61474173  2.34223874]
[-0.56409102 -0.88934947  0.18253626  1.53009048  0.96155976]


# QUESTION 10

In [27]:
arr=np.random.randn(3,3)
print(arr)
arr1=np.mean(arr,axis=1)
print(arr1)
arr2=arr-arr1
print(arr2)

[[-0.88036953  0.52945082 -0.64361661]
 [ 0.78423444 -0.49723083  2.51633957]
 [ 0.00441196 -1.25951442 -1.7847509 ]]
[-0.33151177  0.93444773 -1.01328445]
[[-0.54885776 -0.40499691  0.36966785]
 [ 1.11574621 -1.43167855  3.52962402]
 [ 0.33592373 -2.19396215 -0.77146644]]


# QUESTION 11

In [30]:
Z = np.random.randn(10,1)
print(Z)
I=np.random.randint(0,len(Z),4)
print(I)
np.add.at(Z,I,1)
print(Z)

[[ 0.1563933 ]
 [ 1.00178154]
 [ 1.45730219]
 [ 0.61943204]
 [-2.00478716]
 [-0.44697143]
 [ 0.08368805]
 [ 1.77308629]
 [-0.20806647]
 [ 0.50796768]]
[5 6 2 5]
[[ 0.1563933 ]
 [ 1.00178154]
 [ 2.45730219]
 [ 0.61943204]
 [-2.00478716]
 [ 1.55302857]
 [ 1.08368805]
 [ 1.77308629]
 [-0.20806647]
 [ 0.50796768]]


# QUESTION 12

In [31]:
u=np.random.randn(3,3)
print('Frist array :-')
print(u)
v=np.random.randn(3,3)
print('Second array :-')
print(v)
w=np.dot(u,v)
print('Dot product :-')
print(w)
z=np.diag(w)
print('Diagonal element of Dot Product :-')
print(z)

Frist array :-
[[ 0.29618256  0.45123601 -0.89933649]
 [ 1.42140994 -0.00455723 -0.84372539]
 [ 1.5292807  -1.33461704  0.08869672]]
Second array :-
[[ 0.09177167 -0.08857866 -0.80140842]
 [ 0.61699072  0.03118614 -0.62885955]
 [ 0.38345038  1.33896398  0.24637952]]
Dot product :-
[[-0.03926132 -1.21634231 -0.74270537]
 [-0.19589342 -1.25576662 -1.34414069]
 [-0.64909088 -0.05832148 -0.36443871]]
Diagonal element of Dot Product :-
[-0.03926132 -1.25576662 -0.36443871]


# QUESTION 13

In [33]:
a=np.array([1,5,3,5,7,6,1,5,8,4,5,9,5])
np.argmax(np.bincount(a))

5

# QUESTION 14

In [34]:
x = np.arange(75)
np.random.shuffle(x)
n = 5
print (x[np.argsort(x)[-n:]])

[70 71 72 73 74]


# QUESTION 15

In [35]:
array = np.array([("LetsUpgrade", 10, 15.50),
              ("AI-ML", 20, 30.75)])
rec = np.core.records.fromarrays(arr.T, names='col1, col2, col3')
print("Regular array : \n",array)
print("Record array : \n",rec)

Regular array : 
 [['LetsUpgrade' '10' '15.5']
 ['AI-ML' '20' '30.75']]
Record array : 
 [(-0.88036953,  0.52945082, -0.64361661)
 ( 0.78423444, -0.49723083,  2.51633957)
 ( 0.00441196, -1.25951442, -1.7847509 )]
